### ISSUE TITLE
What's the diffrent between U-net and WU-net?

### ISSUE THREAD

**Issue by kangyang94** [MrGiovanni/Nested-UNet#1]
Through your code , U-net and WU-net have the same architecture, just the dimension of input is different. So what's the diffrent between U-net and WU-net?

**Comment by MrGiovanni** [comment]
Although UNet++ achieves better performance than U-Net, the number of UNet++ also increases, specifically U-Net (7.76M) vs UNet++ (9.04M). It's possible that the performance boost is coming from the increased number of learn-able parameters. Thereby, given the number of UNet++, we compared a "wide" U-Net (9.13M) whose parameter is comparable with UNet++ (9.04M) and a little bit more to avoid the influence of purely increasing the parameter of U-Net like structure.

**Comment by kangyang94** [comment]
Is the performance of wide U-Net better than the original U-net?

**Comment by giovanni-turra** [comment]
[https://arxiv.org/pdf/1807.10165.pdf](url)
